# Generated by Django 2.2.7 on 2020-11-27 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0002_auto_20201126_1433'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='Date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='animal',
            old_name='Description',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='land',
        ),
    ]
