# Generated by Django 2.2.7 on 2020-11-27 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0004_animal_email_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='Farm_name',
            new_name='Farm_Name',
        ),
    ]
