# Generated by Django 2.2.7 on 2020-12-26 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0005_auto_20201127_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='Email_Address',
            field=models.EmailField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='animaltype',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='buyingprice',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='calved',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='category',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='currency',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='profilepic',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
