# Generated by Django 2.2.7 on 2020-10-29 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hasianda', '0006_auto_20201011_1851'),
        ('crop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='land',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='land', to='hasianda.Hasianda'),
            preserve_default=False,
        ),
    ]
