# Generated by Django 2.2.7 on 2020-10-29 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop', '0002_crop_land'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='Cost_Of_Seeds',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8),
        ),
    ]
