# Generated by Django 2.2.7 on 2020-10-29 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crop', '0003_auto_20201029_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='land',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='land', to='hasianda.Hasianda'),
        ),
    ]
