# Generated by Django 2.2.7 on 2020-11-10 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hasianda', '0006_auto_20201011_1851'),
        ('crop', '0005_auto_20201105_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='Farm_Name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='land', to='hasianda.Hasianda'),
        ),
    ]
