# Generated by Django 2.2.7 on 2020-11-10 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crop', '0006_crop_farm_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crop',
            name='Farm_Name',
        ),
        migrations.CreateModel(
            name='Croptype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('landlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crop.Crop')),
            ],
        ),
    ]
