# Generated by Django 2.2.7 on 2020-11-10 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop', '0007_auto_20201110_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='Farm_name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
