# Generated by Django 2.2.7 on 2020-11-10 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crop', '0008_crop_farm_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Croptype',
        ),
    ]
