# Generated by Django 2.2.7 on 2020-10-01 20:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hasianda', '0002_hasianda_email_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='hasianda',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='date added'),
        ),
    ]
