# Generated by Django 2.2.7 on 2020-10-03 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hasianda', '0004_hasianda_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hasianda',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='farmlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
