# Generated by Django 2.2.7 on 2020-12-20 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hasianda', '0007_auto_20201111_1453'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Farm_Name', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='hasianda.Hasianda')),
                ('Size', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='size', to='hasianda.Hasianda')),
            ],
        ),
    ]
