# Generated by Django 2.2.7 on 2020-12-20 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_reports_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reports',
        ),
    ]
